version: '3'

services:

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend_spring
      - backend_flask
      - frontend

  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./web
    container_name: web
    environment:
      VUE_APP_KAKAO_KEY: ${KAKAO_KEY}

  backend_spring:
    restart: always
    container_name: backend_spring
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/huemap?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}


  backend_flask:
    restart: always
    container_name: backend_flask
    build:
      context: ./data
      dockerfile: Dockerfile
    expose:
      - 5050



